language: cpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-8
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-system1.55-dev
      env: COMPILER=g++-8
